'use client';
import {useEffect,useState} from 'react';
type User={id:string;name:string;email:string};
type Item={id:string;seller_id:string;seller_name:string;title:string;brand:string;category:string;condition:string;description:string;price_cents:number;image_key:string;status:string};
type Order={id:string;title:string;amount_cents:number;status:string;created_at:string};
type ListingsResponse={listings:Item[]};
type OrdersResponse={orders:Order[]};
type UserResponse={user:User|null};
type ConnectStatusResponse={ready?:boolean;status?:string};
type ActionResponse={url?:string;error?:string};
const categories=['All','Clothing','Shoes','Accessories','Fragrance','Decants','Bottles'];
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
const signin='/signin-with-chatgpt?return_to=%2F';
export default function Home(){
 const [user,setUser]=useState<User|null>(null),[items,setItems]=useState<Item[]>([]),[mine,setMine]=useState<Item[]>([]),[orders,setOrders]=useState<Order[]>([]);
 const [view,setView]=useState<'shop'|'sell'|'account'>('shop'),[category,setCategory]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Item|null>(null),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[checkoutError,setCheckoutError]=useState(''),[connectReady,setConnectReady]=useState(false),[connectStatus,setConnectStatus]=useState('not_connected');
 async function refresh(){try{const r=await fetch('/api/listings');if(!r.ok)throw Error('Listings could not load. Please refresh.');setItems((await r.json() as any).listings);setError('')}catch(e){setError(e instanceof Error?e.message:'Listings unavailable')}}
 async function account(){const [a,b]=await Promise.all([fetch('/api/listings?mine=1'),fetch('/api/orders')]);if(a.ok)setMine((await a.json() as ListingsResponse).listings);if(b.ok)setOrders((await b.json() as OrdersResponse).orders);try{const c=await fetch('/api/connect/status');if(c.ok){const x=await c.json() as ConnectStatusResponse;setConnectReady(!!x.ready);setConnectStatus(x.status||'not_connected')}}catch{setConnectStatus('unavailable')}}
 useEffect(()=>{fetch('/api/me').then(r=>r.json()).then((x:any)=>setUser(x.user)).catch(()=>{});refresh()},[]);
 useEffect(()=>{if(user)account()},[user]);
 useEffect(()=>{if(!photo){setPreview('');return}const u=URL.createObjectURL(photo);setPreview(u);return()=>URL.revokeObjectURL(u)},[photo]);
 const navigate=(v:'shop'|'sell'|'account')=>{setView(v);setSelected(null);window.scrollTo({top:0,behavior:'smooth'})};
 const filtered=items.filter(x=>(category==='All'||x.category===category)&&(`${x.title} ${x.brand} ${x.description}`).toLowerCase().includes(query.toLowerCase()));
 async function publish(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!photo){setMessage('Add a photo of the item.');return}setBusy(true);try{const form=e.currentTarget,d=new FormData(form),upload=new FormData();upload.set('photo',photo);setMessage('Uploading photo...');const r=await fetch('/api/upload',{method:'POST',body:upload}),image:any=await r.json();if(!r.ok)throw Error(image.error||'Upload failed');setMessage('Publishing...');const saved=await fetch('/api/listings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:d.get('title'),brand:d.get('brand'),category:d.get('category'),condition:d.get('condition'),description:d.get('description'),price:d.get('price'),imageKey:image.key})}),result:any=await saved.json();if(!saved.ok)throw Error(result.error||'Could not publish');form.reset();setPhoto(null);await Promise.all([refresh(),account()]);setMessage('Your listing is live.');navigate('account')}catch(e){setMessage(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 async function status(x:Item,next:string){setBusy(true);try{const r=await fetch('/api/listings/'+x.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});if(!r.ok)throw Error('Could not update listing');await Promise.all([refresh(),account()]);setMessage('Listing updated.')}catch{setMessage('Could not update listing.')}finally{setBusy(false)}}
 async function connectStripe(){setBusy(true);setMessage('Opening Stripe seller onboarding...');try{const r=await fetch('/api/connect/onboard',{method:'POST'}),data=await r.json() as ActionResponse;if(!r.ok||!data.url)throw Error(data.error||'Could not start Stripe onboarding.');window.location.assign(data.url)}catch(e){setMessage(e instanceof Error?e.message:'Could not start Stripe onboarding.')}finally{setBusy(false)}}
 async function buySelected(){if(!selected)return;if(!user){window.location.assign(signin);return}setCheckoutError('');setBusy(true);try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId:selected.id})}),data=await r.json() as ActionResponse;if(!r.ok||!data.url)throw Error(data.error||'Could not start checkout.');window.location.assign(data.url)}catch(e){setCheckoutError(e instanceof Error?e.message:'Could not start checkout.')}finally{setBusy(false)}}
 return <><div className="promo">CULTURE & MIST <span>FASHION · FRAGRANCE · LIFESTYLE</span></div><header className="site-header"><div className="header-main"><button className="brand" onClick={()=>navigate('shop')}><span className="monogram">C<span>&</span>M</span><span className="brand-name">CULTURE & MIST</span></button><label className="header-search">⌕ <input aria-label="Search listings" placeholder="Search pieces, brands, or scents" value={query} onChange={e=>{setQuery(e.target.value);navigate('shop')}}/></label><nav className="header-actions"><button onClick={()=>navigate('shop')}>Shop</button><button onClick={()=>navigate('sell')}>Sell</button>{user?<button onClick={()=>navigate('account')}>My account</button>:<a href={signin} target="_top">Sign in</a>}</nav></div><div className="nav-links">{categories.map(c=><button key={c} className={category===c?'current':''} onClick={()=>{setCategory(c);navigate('shop')}}>{c==='All'?'Discover':c==='Shoes'?'Sneakers':c}</button>)}</div></header>
 <main>{view==='shop'&&<><section className="market-hero"><div><span className="eyebrow">THE MARKETPLACE FOR STYLE + SCENT</span><h1>Find your next<br/><em>favorite thing.</em></h1><p>Shop fashion and fragrance listed by the community, or give your own pieces a new home.</p><button className="primary-btn" onClick={()=>navigate('sell')}>List an item</button></div><div className="market-photo" role="img" aria-label="Fashion and fragrance editorial photograph"/></section><section className="market-section"><div className="section-header"><div><span className="eyebrow">THE MARKETPLACE</span><h2>Fresh listings<span className="period">.</span></h2></div><p>Fixed prices from individual sellers.</p></div>{error?<p className="alert">{error}</p>:<div className="products">{filtered.map(x=><button className="listing-card" key={x.id} onClick={()=>setSelected(x)}><div className="listing-image"><img src={'/api/photo/'+x.image_key} alt={x.title}/></div><div className="product-meta"><span className="brand-label">{x.brand}</span><h3>{x.title}</h3><p>{x.condition} · {x.category}</p><strong>{money(x.price_cents)}</strong></div></button>)}</div>}{!error&&!filtered.length&&<div className="empty-market"><h3>{query||category!=='All'?'No matches yet.':'Be first to list.'}</h3><p>{query||category!=='All'?'Try another search or category.':'The marketplace is ready for its first sellers.'}</p><button className="primary-btn" onClick={()=>navigate('sell')}>Start selling</button></div>}</section></>}
 {view==='sell'&&<section className="seller-workspace"><div className="workspace-heading"><span className="eyebrow">SELL ON CULTURE & MIST</span><h1>List your item.</h1><p>Upload a photo, set one price, and publish. The planned marketplace fee is 2% on completed sales, before payment processing costs.</p></div>{!user?<div className="signin-card"><h2>Create your seller account</h2><p>Sign in with ChatGPT to create and manage listings.</p><a className="primary-btn" href={signin} target="_top">Sign in with ChatGPT</a></div>:<form className="seller-form" onSubmit={publish}><div className="photo-field"><label htmlFor="photo">ITEM PHOTO</label><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/>{preview?<img src={preview} alt="Selected item preview"/>:<span>JPG, PNG, or WebP · up to 5 MB</span>}</div><div className="form-fields"><label>Item name<input name="title" required maxLength={100} placeholder="Vintage leather jacket"/></label><label>Brand<input name="brand" required maxLength={60} placeholder="Brand or designer"/></label><div className="form-pair"><label>Category<select name="category">{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>Condition<select name="condition"><option>New</option><option>Like new</option><option>Excellent</option><option>Good</option><option>Fair</option></select></label></div><label>Description<textarea name="description" required maxLength={2000} rows={5} placeholder="Size, condition, measurements, fill level, flaws..."/></label><label>Price (USD)<input name="price" type="number" required min="1" max="100000" step="0.01" placeholder="0.00"/></label><button className="primary-btn" disabled={busy}>{busy?'Please wait...':'Publish listing'}</button>{message&&<p role="status">{message}</p>}</div></form>}</section>}
 {view==='account'&&<section className="seller-workspace"><div className="workspace-heading"><span className="eyebrow">YOUR ACCOUNT</span><h1>Seller dashboard.</h1><p>{user?'Signed in as '+user.email:'Sign in to manage your listings.'}</p></div>{user?<><div className="signin-card"><h2>Stripe payouts</h2><p>{connectReady?'Your Stripe payout account is ready.':connectStatus==='not_connected'?'Connect Stripe to receive payouts from sales.':connectStatus==='unavailable'?'Stripe status is temporarily unavailable.':'Finish Stripe verification to receive payouts.'}</p>{!connectReady&&<button className="primary-btn" disabled={busy} onClick={connectStripe}>{busy?'Please wait...':connectStatus==='not_connected'?'Connect with Stripe':'Continue Stripe setup'}</button>}</div><div className="dashboard-top"><h2>Your listings</h2><button className="primary-btn" onClick={()=>navigate('sell')}>List another item</button></div>{mine.length?<div className="dashboard-list">{mine.map(x=><div className="dashboard-item" key={x.id}><img src={'/api/photo/'+x.image_key} alt=""/><div><h3>{x.title}</h3><p>{money(x.price_cents)} · {x.status}</p></div>{x.status!=='sold'&&<button disabled={busy} onClick={()=>status(x,x.status==='active'?'withdrawn':'active')}>{x.status==='active'?'Remove from sale':'Relist'}</button>}</div>)}</div>:<p>No listings yet.</p>}<div className="dashboard-top"><h2>Sales</h2></div>{orders.length?orders.map(o=><div className="dashboard-item" key={o.id}><h3>{o.title}</h3><p>{money(o.amount_cents)} · {o.status}</p></div>):<p>No sales yet. Paid orders appear here after Stripe confirms payment.</p>}{message&&<p role="status">{message}</p>}</>:<a className="primary-btn" href={signin} target="_top">Sign in with ChatGPT</a>}</section>}</main>
 <footer><img className="approved-logo" src="/assets/logo.png" alt="Culture & Mist — Fashion, Fragrances, Lifestyle"/><p>Fashion and fragrance from the community.</p><small>© 2026 Culture & Mist</small></footer>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><aside className="drawer" role="dialog" aria-modal="true" aria-label={selected.title} onClick={e=>e.stopPropagation()}><button className="drawer-close" aria-label="Close" onClick={()=>setSelected(null)}>×</button><img className="detail-image" src={'/api/photo/'+selected.image_key} alt={selected.title}/><span className="eyebrow">{selected.category} · {selected.condition}</span><h2>{selected.title}</h2><p>{selected.brand}</p><strong className="detail-price">{money(selected.price_cents)}</strong><p>{selected.description}</p><p>Listed by {selected.seller_name}</p><button className="primary-btn" disabled={busy||selected.seller_id===user?.id} onClick={buySelected}>{!user?'Sign in to buy':selected.seller_id===user.id?'Your own listing':busy?'Opening checkout...':'Continue to secure checkout'}</button>{checkoutError&&<p role="status">{checkoutError}</p>}<p className="checkout-note">Secure payment is handled by Stripe. A sale is confirmed only after Stripe verifies payment.</p></aside></div>}</>
}
